### ISSUE TITLE
Functions to make comunicate back and front

### ISSUE THREAD

**Issue by giuseppemontagner** [PietroHfarm/swdevel-lab-hfarm#16]
start the functions creation

**Comment by giuseppemontagner** [comment]
first try here 9b2591871f8c64f10839bbe39f6880968ae83229

**Comment by giuseppemontagner** [comment]
added also esercizi and farmacie in d3d34035da713b1b09c02116a195a741b50d1ea7

**Comment by giuseppemontagner** [comment]
first try to see if the data are displayed in 5815499f84c97c9a58a70db424b8777891e4236f

**Comment by petruszugni** [comment]
form creation in 0425ff824b2a0aa3893d0b13c6570456532e442a

**Comment by petruszugni** [comment]
improve function in e09b6d0105e1430c9764bb278b7fae5d393b9989

**Comment by annaalongo** [comment]
we add some fuctions in the commit 6e74269c36a0949b021fd1c2efbed34e6cf913b2

**Comment by annaalongo** [comment]
correction of some errors c0607e90c08ed9b5516fe0a2213505ec24ce60d1
