### ISSUE TITLE
Displaying functions

### ISSUE THREAD

**Issue by trapaki** [PietroHfarm/swdevel-lab-hfarm#20]
First, try on displaying the data obtained with the function

**Comment by trapaki** [comment]
update on the last commit here b6cc3974d14645dd667d3fa1625e790faa22817c

**Comment by trapaki** [comment]
adding markers on bfd09fecab2a08178b54dad364cd86ac938d0229

**Comment by annaalongo** [comment]
corrections in d309ab833b8f660a0ad0de774c63684c4077ff40

**Comment by annaalongo** [comment]
closed in 94501e5f218e8e513e2a432e7871a6d93482f525
