### ISSUE TITLE
Cohesion pep8 frontend

### ISSUE THREAD

**Issue by annaalongo** [PietroHfarm/swdevel-lab-hfarm#31]
Cohesion pep8 frontend.

**Comment by giuseppemontagner** [comment]
merged the test branch here 3b2406233f37f98ba5ca7b4157223e5173638129

**Comment by PietroHfarm** [comment]
c4791dd4fb7dbd94fe992206cbf18d8a7a5f39c0

**Comment by annaalongo** [comment]
abdb58b4c8714a210b5b53d28478b214ae144948 frontend

**Comment by trapaki** [comment]
PEP-8 test_main on 13f2121d7b74e47e3c463f40429241e9d6c54d13
