### ISSUE TITLE
adding docstring

### ISSUE THREAD

**Issue by annaalongo** [PietroHfarm/swdevel-lab-hfarm#34]

**Comment by trapaki** [comment]
docstring and comments on 2c5c6df5b1edfcb8b903a5f9689e0452c571f413

**Comment by trapaki** [comment]
docstring 9827b88c56eda610cb4bc040da6a0a15066b8c05

**Comment by trapaki** [comment]
comments and docstring on 7db0572547634cf12b4eac1dd4b0ae45d7da7ee9

**Comment by trapaki** [comment]
PEP-8 after comments fbad7202bac07c48eb201a43c31660384ee1e473

**Comment by trapaki** [comment]
fixing 03844f99246b445b926488005f4e0f75c3e9b2a6
