### ISSUE TITLE
Final remediation steps 

### ISSUE THREAD

**Issue by giuseppemontagner** [PietroHfarm/swdevel-lab-hfarm#42]
Correcting the mistakes made in the first version based on the suggestions received

**Comment by giuseppemontagner** [comment]
First modifications here 02b341932c6905d2b8634c3a05c9d7d81672b6c7

**Comment by annaalongo** [comment]
fixing some errors in 718a0ce38d4bc8b861e7e1e0bd35ff21b2541386

**Comment by annaalongo** [comment]
corrections frontend in 5b8cdbaa9cf85ee6e0f1b0a2dee514b414d54d36

**Comment by annaalongo** [comment]
translation of some names from Italian to English here 833e43442fad8c334513407226130eec84b0feb1

**Comment by giuseppemontagner** [comment]
other modifications about documentation and translation here 007267f2b09cc3aa92d416608faf804c8872d9ad

**Comment by giuseppemontagner** [comment]
Closing the issue with the merge here ffe25948989f39da88d736ee1276156b894f4826
